version: '3.8'
services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - traefik_test_general
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontent.rule=Host(`ehis.codelearnit.io.vn`)"
      - "traefik.http.routers.frontent.entrypoints=websecure"
      - "traefik.http.routers.frontent.tls.certresolver=lets-encrypt"
      - "traefik.http.services.frontent.loadbalancer.server.port=3000"
    restart: always
    env_file:
      - .env.product

networks:
  traefik_test_general:
    external: true